name = "vpn"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true

[[kv_namespaces]]
binding = "SIREN"
id = "26d329db7be646f3b8d3cf43ab1b2700"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "aaaaaaa1-bbbb-4ccc-addd-eeeeeeeeeee1"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/NoLimiter21/vpn/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/NoLimiter21/vpn/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/NoLimiter21/vpn/refs/heads/master/web/link.html"
CONVERTER_PAGE_URL = "https://raw.githubusercontent.com/NoLimiter21/vpn/refs/heads/master/web/converter.html"
